// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJUe7kVnL0Rdj83BRIUENmKLqROvK0osc',
    appId: '1:324719605583:web:fd52895dd5ff4af95ef73a',
    messagingSenderId: '324719605583',
    projectId: 'kichukini2',
    authDomain: 'kichukini2.firebaseapp.com',
    storageBucket: 'kichukini2.firebasestorage.app',
    measurementId: 'G-H1XYZ7553M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF6by1WmheOydMjQ6KHztGMTxNhv-rGi0',
    appId: '1:324719605583:android:d44ff6955573feca5ef73a',
    messagingSenderId: '324719605583',
    projectId: 'kichukini2',
    storageBucket: 'kichukini2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxxi-ia2HOUnEJ1rqw2Hn0Z-QkJHf9V4c',
    appId: '1:324719605583:ios:de86b5dce932f1c75ef73a',
    messagingSenderId: '324719605583',
    projectId: 'kichukini2',
    storageBucket: 'kichukini2.firebasestorage.app',
    iosBundleId: 'com.example.kichukini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxxi-ia2HOUnEJ1rqw2Hn0Z-QkJHf9V4c',
    appId: '1:324719605583:ios:de86b5dce932f1c75ef73a',
    messagingSenderId: '324719605583',
    projectId: 'kichukini2',
    storageBucket: 'kichukini2.firebasestorage.app',
    iosBundleId: 'com.example.kichukini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJUe7kVnL0Rdj83BRIUENmKLqROvK0osc',
    appId: '1:324719605583:web:b16e61c0806332c45ef73a',
    messagingSenderId: '324719605583',
    projectId: 'kichukini2',
    authDomain: 'kichukini2.firebaseapp.com',
    storageBucket: 'kichukini2.firebasestorage.app',
    measurementId: 'G-Q6PZ78L0L5',
  );
}
